[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
ciborium = "0.2"

[build-dependencies]
risc0-build = { version = "^3.0.3" }

[package.metadata.risc0]
methods = ["guest"]
